### ISSUE TITLE
Build failure during Python module testing

### ISSUE THREAD

**Issue by macrotex** [rra/remctl#27] opened 2019-11-03 18:41 UTC
1. Cloned git repository.
2. `$ git checkout debian/master`
3. `$ gbp buildpackage`
4. Errors:
```make[3]: Leaving directory '/build/remctl-3.16/php'
...
Testing Python extension
running pytest
Searching for typing
Reading https://pypi.org/simple/typing/
Download error on https://pypi.org/simple/typing/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
Couldn't find index page for 'typing' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
No local packages or working download links found for typing
error: Could not find suitable distribution for Requirement.parse('typing')
make[2]: *** [Makefile:4625: check-local] Error 1```

**Comment by rra** [comment] 2019-11-03 18:49
What version of Python 3 are you trying to build it with? typing was first included with Python 3 in 3.5, so if you're building against an older version than that (if you're trying to build for jessie, for example), you'll need to add an explicit dependency on python3-typing.

**Comment by rra** [comment] 2019-11-03 19:00
Ah, it looks like jessie may not have included a package of typing for Python 3, so backporting to jessie (if indeed that's the issue) may require some extra work. Is that what's happening? If you're building with Python 3.5 or later, there's something else going on (the build system isn't figuring out typing is already available for some reason).

**Comment by macrotex** [comment] 2019-11-04 13:27
I am building against `sid`. 

The first line of `python/setup.py` is `#!/usr/bin/env python`. Should that be `#!/usr/bin/env python3`?

**Comment by rra** [comment] 2019-11-04 16:55
It won't make any difference -- that line isn't used by the Debian build.

I can't reproduce this problem; it works fine in sid for me. You're using `gbp buildpackage`, so it should be building in a chroot... maybe the chroot isn't up to date? I'm not sure what's wrong, but the build worked fine on all of the Debian buildds.

**Comment by macrotex** [comment] 2019-11-05 01:43
OK. I will continue to investigate on my end.

**Comment by rra** [comment] 2019-11-05 16:51
Doh, sorry, I completely missed that this was happening during autopkgtest instead of during the regular build. This did also fail in Debian and will be fixed this evening.

**Comment by rra** [comment] 2019-11-06 05:57
So, for the record, this was a great bug report and I was completely wrong about what was happening. I was so certain that Debian buildds didn't support network access, and that my personal build environment also didn't, that it didn't even occur to me that this assumption was wrong and that both were accessing the network.

This also broke in Ubuntu because it really doesn't allow Internet access, and even then I didn't entirely understand the problem and thought it was specific to autopkgtest, when it's not.

Anyway, many apologies for not understanding the problem, and it should now be fixed in the debian branch and (in a different way) on master.

**Closed by rra** 2019-11-06 05:57 UTC
